name: 🚀 release


on:
  push:
    branches:
      - main

jobs:
    release:
        name: 🚀 release
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout Repo
              uses: actions/checkout@master
            - name: 🟢 Setup node
              uses: actions/setup-node@master
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org
            - name: 🟢 install dependencies
            - run: npm install
            
            - name: 📄 test
              run: npm test
              
            - name: 🚀 publish
              run: npm publish --access public
              
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
